import { Providers } from '@/lib/Provider'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = {
  children: React.ReactNode
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang='kr'>
      <body suppressHydrationWarning={true} className='relative bg-slate-200'>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
